Task/№6 personal task
LarionovKirill/Programming pull request #11
Opened 2023-04-22 06:53 UTC by LarionovKirill

2023-04-25 14:58 UTC, Ershovoy requested changes

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +            var jsonString = File.ReadAllText(path);
![image](https://user-images.githubusercontent.com/50287099/234297884-c48affc1-7ffa-4302-88da-70b04bb62fa2.png)

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                    );
Закрывающая скоба в параметрах фунции не переносится на отдельную строку, оставляй на предыдущей.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                PersonalTask.Services.ColissionManager.AssertOnLengthOfString(
Можно сократить с PersonalTask.Services... до Services...
PersonalTask пространство имён относится ко всему проекту, так что упоминать его смысла внутри проекта явно нет. Читаемости кода это не добавляет, но из-за этого приходится больше печатать, а это оу шит как плохо. Я знаю тебе очень хочется, у всех же свой стиль кода йоу. Но не вини меня, вини общество.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/FlightType.cs
> +        Международный
Русский... Серьёзно?

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/Services/ColissionManager.cs
> +        public static void AssertOnLengthOfString(string text, int maxLength, string propertyName)
3 армугент называется propertyName, а в XML комметарии описано, что это текст ошибки.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                    "Длина строки не должна превышать 100 символов.");
Текст ошибки лучше поместить внутрь метода, чтобы не приходилось на каждый вызов писать одно и тоже. Сделай сообщение обобщённым и передавай в аргументы имя свойства, чтобы программист знал какое свойство вызвало исключение.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +        List<Model.AirTravel> _airTravels = new List<Model.AirTravel>();
Вид доступа к члену класса всегда должен быть явно указан.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +                    airTravelsListBox.Items.Add(CreateStringForList(_airTravels.Last()));
Ну что за позореще, мне. 
Каждая инструкция должна располагаться на отдельной строке, в таком случае код удобнее читать и пробегать по нему дебагером. Конечно не нужно прям каждую малешую инструкцию рассписывать на отдельные строки, но и в такой раш, как ты входить не нужно. Пять функций вызвал в одной строчке, пять, Карл!

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +                    if (_airTravels[j].DepartureTime > _airTravels[j + 1].DepartureTime)
У тебя же есть закрытое свойство для поля _airTravels, обращайся через него. Объяснял почему лучше так делать в прошлом или позапрошлом пуле.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.Designer.cs
> +        private void InitializeComponent()
По заданию в программе должна быть адаптивная вёрстка.

2023-04-25 14:58 UTC, Ershovoy commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +        private void ChangePictureBox_Click(object sender, EventArgs e)
https://user-images.githubusercontent.com/50287099/234318039-b94903df-7bde-4a3c-b195-aaf810a089b6.mp4

2023-04-25 15:07 UTC, LarionovKirill commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                PersonalTask.Services.ColissionManager.AssertOnLengthOfString(
Бро, понимаю тебя, народ прогнил, во всём виноваты люди

2023-04-25 15:07 UTC, LarionovKirill commented on PersonalTask/PersonalTask/Model/FlightType.cs
> +        Международный
А что нет?

2023-04-25 15:09 UTC, LarionovKirill commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +                    if (_airTravels[j].DepartureTime > _airTravels[j + 1].DepartureTime)
Тут я забыл про него видимо

2023-04-25 16:36 UTC, LarionovKirill commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +            var jsonString = File.ReadAllText(path);
Я забыл, что он в bin файле. Сейчас буду пробовать достать файл из ресурсов. Но не уверен, что получится.

2023-04-26 04:05 UTC, LarionovKirill commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.Designer.cs
> +        private void InitializeComponent()
Я так и не разобрался со свойство anchor

2023-04-26 04:30 UTC, LarionovKirill commented on PersonalTask/PersonalTask/View/Interfaces/UserInterface.cs
> +        private void ChangePictureBox_Click(object sender, EventArgs e)
Исправил это баг

2023-04-26 23:33 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                PersonalTask.Services.ColissionManager.AssertOnLengthOfString(
Не забый про nameof(). Он поможет избавиться от константной строки, что в свою очередь обеспечит полностью автоматическое переименование поля.

2023-04-26 23:35 UTC, Ershovoy commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                    "Длина строки не должна превышать 100 символов.");
Не забый про nameof(). Он поможет избавиться от константной строки, что в свою очередь обеспечит полностью автоматическое переименование поля.

2023-04-27 03:02 UTC, LarionovKirill commented on PersonalTask/PersonalTask/Model/AirTravel.cs
> +                    "Длина строки не должна превышать 100 символов.");
Ок, исправлю

2023-05-02 11:46 UTC, merged