Oop №1
LarionovKirill/Programming pull request #12
Opened 2023-04-24 12:53 UTC by LarionovKirill

2023-05-11 07:42 UTC, Ershovoy requested changes

2023-05-11 07:42 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/CustomerTab.cs
> +        }
Не хватает логики по редактированию данных о товаре и о клиенте. Данные после валидации никуда не идут. Валидацию из View можно вообще убрать, так как она уже происходит в Model.

2023-05-11 07:42 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		static private int _id;
Лишнее статическое закрытое поле, которое нигде не используется. Ниже у тебя есть **public int Id { get; private set; }** это авто свойство, при их использовании явно создавать закрытое поле не нужно, оно создаёт само. В **Customer.cs** такая же история.

2023-05-11 07:42 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/MainForm.cs
> +    public partial class MainForm : Form
Не хватает адаптивной верстки

2023-05-11 07:42 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/CustomerTab.cs
> +    public partial class CustomerTab : UserControl
Не хватает XML комментариев для класса и методов.

2023-05-11 07:42 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		private double _cost;
Для всего где требуется точные значение и ни в коем случае не допускаются погрешности, используется тип данных decimal. Double и float не точно представляют числа с плавающей точной (после определённого знака), но быстрее вычисляютсяя процессором. Может видел мемы где сравнивают два казалось бы одинаковых числа, но получают в результате false. Например 3 + 0.5 **не** равно 3.5, а равно что-то типо 3.50000134. Ходят легенды, что в ранней версии сбербанка была такого рода ошибка и некоторые успели ненадолго стать миллионерами.

2023-05-11 08:06 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/MainForm.cs
> +    public partial class MainForm : Form
Блин, в первой забыл добавить(
Сделаю

2023-05-11 08:08 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		static private int _id;
Вопрос про автосвойства. Предпочтение отдается им? Просто у меня немного как понимание с с++ и нужно сначала создать поле, а потом к нему геттер и сеттер, ну если так, то получается что почти весь класс должен состоять только из автосвойств?

2023-05-11 08:09 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/MainForm.cs
> +    public partial class MainForm : Form
Да уже увидел, что во второй есть. Тогда можешь не добавлять, наверное, тогда.

2023-05-11 08:11 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/MainForm.cs
> +    public partial class MainForm : Form
Ну если учитывать ветку develop, то да, добавится уже там

2023-05-11 08:23 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		private double _cost;
Decimal тип занимает больше памяти и поэтому погрешность меньше?

2023-05-11 08:41 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/CustomerTab.cs
> +        }
Согласен, бред какой-то сделал, но уже исправил.

2023-05-11 08:41 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/CustomerTab.cs
> +    public partial class CustomerTab : UserControl
Сделал.

2023-05-14 09:12 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		static private int _id;
Если в геттере или сеттере нету никакой логики, то лучше использовать автосвойство. Вдруг в будущем появится логика при обращении к полю или его присваивании, которую ты поместишь в геттер/сеттер свойства. В таком случае тебе не придётся во всем классе переименовывать _films в Films. И это ещё в лучшем случае, когда ты знаешь, что тебе нужно это сделать.

2023-05-14 09:14 UTC, merged