Oop№4   inheritance
LarionovKirill/Programming pull request #31
Opened 2023-05-13 14:43 UTC by LarionovKirill

2023-05-22 15:58 UTC, Ershovoy requested changes

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +        }
Слишком большая вложенность кода. Для решения этого можешь инвентировать if условия.

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +                        }
У тебя в SelectedItem уже хранится нужное перечисление, этот цикл здесь вообще не к месту.

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +            costLabel.Text = order.FullCost.ToString();
Дублирование кода с методом ниже (FillPriorityOrder).

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Customer.cs
> +		public Address Address { get; set; }
Почему возникла необходисть в использовании этих атрибутов?

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/bin/Debug/OOP.exe
Настрой .gitignore, пожалуйста

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Services/CustomerGenerator.cs
> +            List<Model.Customer> _customers = new List<Model.Customer>();
Не забывай как именовать локальные переменные

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Services/CustomerGenerator.cs
> +        }
Такой подход к генерации пользователей приводит к следующем проблемам:
1. Если я захочу изменить количество сгенерированных пользователей, то мне для этого нужно будет удалить строку, что приводит к потере информации о городах, улицах, именах. Из-за чего придётся заново их выдумывать, в случае увеличении количества покупателей на выходе.
2. Или допустим я захочу расширить список используемых городов, стран для тестов, без изменения количества покупателей. В такой реализации это невозможно.
Подумай как эти проблемы можно решить.

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/CartsTab.cs
> +            }
Используй одну пустую строку между логическими частями в методе. Так как сплошной код усложняют восприятие и увеличивают возможность ошибки. Две первые строки отвечают за очистку списка, а две последующие за его наполнение. Две различные задачи, занимающие несколько строк, поэтому для удобства читаемости между ними можно провести границу пустой строкой. Здесь это не так заметно, но в некоторых местах у тебя прослеживается тенденция этого не делать.

2023-05-22 15:58 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.Designer.cs
> +    partial class ordersTab
Просматривать таблицы в такую щель не особо удобно. Я, как со стороны пользователя, хотель бы менять соотношение пространства занимаемого таблице и полями. Используй для этого Splitter. Ты программист, ты создаешь продукт для пользователей, нужно думать о будущем опыте использования написанного тобой продукта. Это даже выглядит не эстетично, когда при раскрытом на весь экран приложении 75 процентов пространства пустеет.
![image](https://github.com/LarionovKirill/Programming/assets/50287099/f96d4271-7adc-4f80-8d13-18a5392e6149)

2023-05-22 16:20 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Customer.cs
> +		public Address Address { get; set; }
Потому что виджуалка иногда играет с тобой в игру и говорит, что пол твоего кода не компилируется по непонятным причинам.
Вот код ошибки:
![image](https://github.com/LarionovKirill/Programming/assets/122218338/65a96217-1eab-4564-8562-5f338d052d52)

2023-05-22 16:21 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/bin/Debug/OOP.exe
Что-то лишнее попало?

2023-05-22 16:21 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Services/CustomerGenerator.cs
> +        }
Понял, исправлю

2023-05-23 05:00 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +                        }
У меня там словарь, потому что 9:00-11:00 в перечисление не записать, поэтому я там перебираю и нахожу нужные значение и ключ в цикле.
Просто по значению я не могу присвоить

2023-05-23 05:03 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.Designer.cs
> +    partial class ordersTab
Исправил

2023-05-23 05:04 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Services/CustomerGenerator.cs
> +        }
Исправил

2023-05-23 05:04 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Services/CustomerGenerator.cs
> +            List<Model.Customer> _customers = new List<Model.Customer>();
Исправил

2023-05-23 05:04 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +            costLabel.Text = order.FullCost.ToString();
Исправил

2023-05-23 05:05 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +        }
Немного уменьшил

2023-05-23 14:15 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/bin/Debug/OOP.exe
У тебя в каждом коммите идут лишние файлы
![image](https://github.com/LarionovKirill/Programming/assets/50287099/732e4e4a-fbad-4bbf-965c-e2721ff4f96c)
![image](https://github.com/LarionovKirill/Programming/assets/50287099/c5b41eaf-3afd-4aa0-981d-ceb1635e4c0d)

2023-05-23 14:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +        }
if (informationTable.CurrentRow == null)
{
    return;
}

var index = informationTable.CurrentRow.Index;
if (index < 0)
{
    return;
}

var selectedOrder = Orders[index];
if (selectedOrder is not PriorityOrder)
{
    return;
}

var selectedPriorityOrder = (PriorityOrder)selectedOrder;
var dictionary = Services.EnumGetter.GetDeliveryTime();
foreach (var time in dictionary)
{
    if (time.Value == deliveryTimeComboBox.SelectedItem.ToString())
    {
        selectedPriorityOrder.DeliveryTime = time.Key;
        break;
    }
}
Orders[index] = selectedPriorityOrder;

2023-05-23 14:33 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +        }
То есть надо его разбивать на те моменты, где его можно исключить?

2023-05-23 14:43 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/OrdersTab.cs
> +                        }
Так у словарь, где ключём идёт строка, а значением перечисление. Ты можешь получить его значение по ключу так: dictionary[keyValie]. Чтобы постоянно в разных местах кода не перебирать список в ручную. Это не только уменьшит количество кода в будущем, но и упростит работу с ним

2023-05-29 06:22 UTC, merged