Oop№6   standart interfaces
LarionovKirill/Programming pull request #33
Opened 2023-05-25 16:37 UTC by LarionovKirill

2023-06-01 03:29 UTC, Ershovoy requested changes

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Diagrams/UML лаба 6.jpg
Отношение реализация (пунктирная незакрашенная стрелка) идет от класса к интерфейсу, который он реализует. По варианту UML лучше оставляй первую. Я ещё подумаю как можно это всё уместить, но что-то мне кажется тут лаконичного варианта нету.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Address.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Address.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Cart.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Cart.cs
> +            return new Cart().ListOfGoods = this.ListOfGoods;
Три инструкции на одной строке затрудняет понимание кода. Код чаще читается, чем пишется, поэтому не экономь на понятности и чистоте кода ради скорости набора.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Customer.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Discounts/PercentDiscount.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Discounts/PercentDiscount.cs
> +
Лишний разделитель.

2023-06-01 03:29 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		}
Табы вместо пробелов в нескольких местах.

2023-06-01 03:38 UTC, Ershovoy commented
Можешь править замечания сразу в 7 лабе, чтобы потом не пришлось конфликты при слиянии решать.

2023-06-02 15:15 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Address.cs
> +
Исправил

2023-06-02 15:15 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Address.cs
> +
Исправил

2023-06-02 15:15 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Cart.cs
> +
Исправил

2023-06-02 15:17 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Cart.cs
> +            return new Cart().ListOfGoods = this.ListOfGoods;
Исправил.

2023-06-02 15:17 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Customer.cs
> +
Исправил

2023-06-02 15:18 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Discounts/PercentDiscount.cs
> +
Исправил

2023-06-02 15:18 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Discounts/PercentDiscount.cs
> +
Исправил.

2023-06-02 15:22 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Model/Item.cs
> +		}
Постарался везде табы чтоб были.

2023-06-02 15:33 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Diagrams/UML лаба 6.jpg
Исправил.

2023-06-06 04:03 UTC, merged