Oop№7   delegates
LarionovKirill/Programming pull request #34
Opened 2023-05-30 16:59 UTC by LarionovKirill

2023-06-01 04:07 UTC, Ershovoy requested changes

2023-06-01 04:07 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/Services/DataTools.cs
> +            Func<Item, object, bool> compare)
При переносе аргументов, каждый переносится на отдельную строку, включая первый.

2023-06-01 04:07 UTC, Ershovoy commented on ObjectOrientedPractics/OOP/View/Tabs/CartsTab.cs
>  namespace OOP.View.Tabs
Общие элементы в отдельных вкладках не выровнены относительно друг друга. При переключении можно видеть, что растояние от ListBox до края окна отличается, тоже самое и с шириной и другими общими элементами.

https://github.com/LarionovKirill/Programming/assets/50287099/f2dedd07-71aa-4c56-91d7-02792fa1b906

2023-06-02 15:52 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/Services/DataTools.cs
> +            Func<Item, object, bool> compare)
Исправил

2023-06-02 16:10 UTC, LarionovKirill commented on ObjectOrientedPractics/OOP/View/Tabs/CartsTab.cs
>  namespace OOP.View.Tabs
Исправил.

2023-06-10 10:01 UTC, merged